export const SELECT_NODE = 'SELECT_NODE';
export const FILTER_NODES_BY_ID = 'FILTER_NODES_BY_ID';
export const FILTER_NODES_BY_REGIONS = 'FILTER_NODES_BY_REGIONS';
export const REQUEST_NODES = 'REQUEST_NODES';
export const RECEIVED_NODES_SUCCESS = 'RECEIVED_NODES_SUCCESS';
export const RECEIVED_NODES_FAILURE = 'RECEIVED_NODES_FAILURE';
